version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:main-678495a
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  nginx:
    image: nginx:stable
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
    ports:
      - "8080:80"
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/usr/share/nginx/html
    networks:
      - loki

  backend:
    build: ./backend/
    ports:
      - "5001:8080"
    networks:
      - loki

  client1:
    build: ./client/
    networks:
      - loki
  client2:
    build: ./client/
    networks:
      - loki
  client3:
    build: ./client/
    networks:
      - loki

  grafana:
    image: grafana/grafana-enterprise:8.2.3
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./provisioning/dashboards/:/var/lib/grafana/dashboards/
    ports:
      - "3000:3000"
    networks:
      - loki
