{
 "title": "Nginx - Loki",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "QPS per upstream",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (ip)\n  (\n    rate(\n    {compose_service=\"nginx\"}\n    | pattern `<ip> - - [<_>] \"<method> <path> HTTP<_>\" <status> <_> <latency> ` | method != \"\"\n    [$__interval]\n  )\n)"
    }
   ]
  },
  {
   "title": "% Errors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - (\n  sum(count_over_time({compose_service=\"nginx\"} |~ \" 20. \"[$__interval])) /        sum(count_over_time({compose_service=\"nginx\"}[$__interval]))\n)"
    }
   ]
  },
  {
   "title": "Requests /s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "       sum(rate({compose_service=\"nginx\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "SLO (200 and < 10s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - sum(count_over_time({compose_project=\"logql\"} \n  | pattern `<ip> - - [<_>] \"<method> <path> HTTP<_>\" <status> <_> <latency> `\n  | status >= 500 or latency > 10 [$__range]))\n  \n  / \n  sum(count_over_time({compose_project=\"logql\"} \n  | pattern `<ip> - - [<_>] \"<method> <path> HTTP<_>\" <status> <_> <latency> `\n [$__range])) * 100"
    }
   ]
  },
  {
   "title": "QPS per status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path,status)\n  (\n    rate(\n    {compose_service=\"nginx\"}\n    | pattern `<ip> - - [<_>] \"<method> <path> HTTP<_>\" <status> <_> <latency> `\n    [1m]\n  )\n)"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(0.99,{compose_project=\"logql\"} \n  | pattern `<ip> - - [<_>] \"<method> <path> HTTP<_>\" <status> <_> <latency> ` | latency != \"\" | unwrap latency [$__interval]) by (compose_project)"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{compose_service=\"nginx\"} !~ \" 20. \""
    }
   ]
  }
 ]
}